### ISSUE TITLE
Please note my comments

### ISSUE THREAD

**Issue by jakob-r** [mboecker/mlrmbo-webservice#13]
https://github.com/mboecker/mlrmbo-webservice/commit/64c1fa11d0d82003a2f92d8bcc57f73c134d97b3#r30861026

https://github.com/mboecker/mlrmbo-webservice/commit/64c1fa11d0d82003a2f92d8bcc57f73c134d97b3#r30861031

**Comment by mboecker** [comment]
This is now a comment in the code
see https://github.com/mboecker/mlrmbo-webservice/pull/20/files#diff-56fd03f717a2ce152f0a6cc8b7e9c612R108

multiple proposals must use toJSON instead of paste, cat, ...
