### ISSUE TITLE
support +Inf, -Inf in par.set

### ISSUE THREAD

**Issue by mboecker** [mboecker/mlrmbo-webservice#2]

**Comment by jakob-r** [comment]
Why?

**Comment by mboecker** [comment]
Well, the first par.set I tried used these values and it failed, because JSON-encoded "Inf" is a string and not a number.
The par.set I used was generated by "makeNumericParamSet".

**Comment by jakob-r** [comment]
But MBO needs box constrained parameter sets. Meaning: You can spend some work to parse Inf param boundaries but MBO will just give you an error because it needs finite bounds. :wink:

**Comment by mboecker** [comment]
We can close this then.
